### PR TITLE
Removes dependency on ursa, adds pure JS implementation of RSA

### PR DESCRIPTION
**Pull request by benburkhart1**
Ursa is no longer maintained, and has issues with modern versions of NodeJS. This change is a minimal one that removes ursa, and adds in node-rsa.

### CODE REVIEW

**Comment by dhleong** [comment]
Thanks for the PR! Just a minor style request: could you use `NodeRSA`
instead of `rsa`, since it's the name of a class?

Otherwise, this LGTM, and I'll merge it once I get back and test it.

**Comment by benburkhart1** [comment]
Sure thing.

**Comment by dhleong** [comment]
Thanks!

**Comment by dhleong** [comment]
LGTM—Thanks for the PR! Will release shortly as 1.0.1

**Pull request merged**
